# Vivid Life · Twilight · Yellow
# Generated by vivid-life-powershell — do not hand-edit. Edit src/theme-template.mjs and rebuild.

if (-not $PSStyle) {
    Write-Warning 'Vivid Life Theme requires PowerShell 7.2+ ($PSStyle). Skipping theme.'
    return
}

& {
    function Set-VividLifeProperty([scriptblock]$Assign) {
        try { & $Assign } catch { }
    }

    if (Get-Module -ListAvailable -Name PSReadLine) {
        Set-PSReadLineOption -Colors @{
            Default = $PSStyle.Foreground.FromRgb(245, 245, 245)
            Comment = $PSStyle.Foreground.FromRgb(163, 163, 163)
            Keyword = $PSStyle.Foreground.FromRgb(216, 180, 254)
            String = $PSStyle.Foreground.FromRgb(132, 204, 22)
            Number = $PSStyle.Foreground.FromRgb(253, 186, 116)
            Command = $PSStyle.Foreground.FromRgb(234, 179, 8)
            Parameter = $PSStyle.Foreground.FromRgb(249, 115, 22)
            Operator = $PSStyle.Foreground.FromRgb(216, 180, 254)
            Type = $PSStyle.Foreground.FromRgb(234, 179, 8)
            Variable = $PSStyle.Foreground.FromRgb(253, 186, 116)
            Member = $PSStyle.Foreground.FromRgb(147, 197, 253)
            Emphasis = $PSStyle.Foreground.FromRgb(219, 234, 254)
            Error = $PSStyle.Foreground.FromRgb(254, 226, 226)
            ContinuationPrompt = $PSStyle.Foreground.FromRgb(163, 163, 163)
            InlinePrediction = $PSStyle.Foreground.FromRgb(163, 163, 163)
            Selection = $PSStyle.Foreground.FromRgb(245, 245, 245) + $PSStyle.Background.FromRgb(91, 91, 91)
        }

        try {
            Set-PSReadLineOption -Colors @{
                ListPrediction = $PSStyle.Foreground.FromRgb(212, 212, 212)
                ListPredictionSelected = $PSStyle.Foreground.FromRgb(245, 245, 245) + $PSStyle.Background.FromRgb(91, 91, 91)
            }
        } catch { }
    }

    Set-VividLifeProperty { $PSStyle.Formatting.FormatAccent = $PSStyle.Foreground.FromRgb(234, 179, 8) }
    Set-VividLifeProperty { $PSStyle.Formatting.TableHeader = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(234, 179, 8) }
    Set-VividLifeProperty { $PSStyle.Formatting.CustomTableHeaderLabel = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(234, 179, 8) }
    Set-VividLifeProperty { $PSStyle.Formatting.Error = $PSStyle.Foreground.FromRgb(254, 226, 226) }
    Set-VividLifeProperty { $PSStyle.Formatting.ErrorAccent = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(254, 226, 226) }
    Set-VividLifeProperty { $PSStyle.Formatting.Warning = $PSStyle.Foreground.FromRgb(254, 249, 195) }
    Set-VividLifeProperty { $PSStyle.Formatting.Verbose = $PSStyle.Foreground.FromRgb(219, 234, 254) }
    Set-VividLifeProperty { $PSStyle.Formatting.Debug = $PSStyle.Foreground.FromRgb(163, 163, 163) }

    Set-VividLifeProperty { $PSStyle.FileInfo.Directory = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(234, 179, 8) }
    Set-VividLifeProperty { $PSStyle.FileInfo.SymbolicLink = $PSStyle.Foreground.FromRgb(253, 186, 116) }
    Set-VividLifeProperty { $PSStyle.FileInfo.Executable = $PSStyle.Foreground.FromRgb(190, 242, 100) }
}

