# Vivid Life · Noon · Red
# Generated by vivid-life-powershell — do not hand-edit. Edit src/theme-template.mjs and rebuild.

if (-not $PSStyle) {
    Write-Warning 'Vivid Life Theme requires PowerShell 7.2+ ($PSStyle). Skipping theme.'
    return
}

& {
    function Set-VividLifeProperty([scriptblock]$Assign) {
        try { & $Assign } catch { }
    }

    if (Get-Module -ListAvailable -Name PSReadLine) {
        Set-PSReadLineOption -Colors @{
            Default = $PSStyle.Foreground.FromRgb(23, 23, 23)
            Command = $PSStyle.Foreground.FromRgb(185, 28, 28)
            Keyword = $PSStyle.Foreground.FromRgb(126, 34, 206)
            Parameter = $PSStyle.Foreground.FromRgb(63, 98, 18)
            String = $PSStyle.Foreground.FromRgb(54, 83, 20)
            Number = $PSStyle.Foreground.FromRgb(124, 45, 18)
            Variable = $PSStyle.Foreground.FromRgb(124, 45, 18)
            Type = $PSStyle.Foreground.FromRgb(133, 77, 14)
            Member = $PSStyle.Foreground.FromRgb(29, 78, 216)
            Operator = $PSStyle.Foreground.FromRgb(126, 34, 206)
            Comment = $PSStyle.Foreground.FromRgb(82, 82, 82)
            InlinePrediction = $PSStyle.Foreground.FromRgb(82, 82, 82)
            ContinuationPrompt = $PSStyle.Foreground.FromRgb(82, 82, 82)
            Error = $PSStyle.Foreground.FromRgb(127, 29, 29)
            Selection = $PSStyle.Foreground.FromRgb(23, 23, 23) + $PSStyle.Background.FromRgb(254, 215, 215)
            Emphasis = $PSStyle.Foreground.FromRgb(23, 23, 23) + $PSStyle.Background.FromRgb(253, 230, 108)
        }

        try {
            Set-PSReadLineOption -Colors @{
                ListPrediction = $PSStyle.Foreground.FromRgb(23, 23, 23)
                ListPredictionSelected = $PSStyle.Foreground.FromRgb(23, 23, 23) + $PSStyle.Background.FromRgb(242, 214, 214)
            }
        } catch { }
    }

    Set-VividLifeProperty { $PSStyle.Formatting.FormatAccent = $PSStyle.Foreground.FromRgb(185, 28, 28) }
    Set-VividLifeProperty { $PSStyle.Formatting.TableHeader = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(185, 28, 28) }
    Set-VividLifeProperty { $PSStyle.Formatting.CustomTableHeaderLabel = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(185, 28, 28) }
    Set-VividLifeProperty { $PSStyle.Formatting.Error = $PSStyle.Foreground.FromRgb(127, 29, 29) }
    Set-VividLifeProperty { $PSStyle.Formatting.ErrorAccent = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(127, 29, 29) }
    Set-VividLifeProperty { $PSStyle.Formatting.Warning = $PSStyle.Foreground.FromRgb(113, 63, 18) }
    Set-VividLifeProperty { $PSStyle.Formatting.Verbose = $PSStyle.Foreground.FromRgb(30, 58, 138) }
    Set-VividLifeProperty { $PSStyle.Formatting.Debug = $PSStyle.Foreground.FromRgb(82, 82, 82) }

    Set-VividLifeProperty { $PSStyle.FileInfo.Directory = $PSStyle.Bold + $PSStyle.Foreground.FromRgb(185, 28, 28) }
    Set-VividLifeProperty { $PSStyle.FileInfo.SymbolicLink = $PSStyle.Foreground.FromRgb(124, 45, 18) }
    Set-VividLifeProperty { $PSStyle.FileInfo.Executable = $PSStyle.Foreground.FromRgb(54, 83, 20) }
}

